// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: insert_insurance_company.sql

package dbqueries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInsuranceCompany = `-- name: CreateInsuranceCompany :one
INSERT INTO
    insurance_companies (
        type,
        name,
        full_name,
        address,
        phone,
        email,
        website,
        ogrn,
        okpo,
        okato,
        created_ts,
        created_by
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12
    ) RETURNING id
`

type CreateInsuranceCompanyParams struct {
	Type      int32
	Name      string
	FullName  string
	Address   pgtype.Text
	Phone     pgtype.Text
	Email     pgtype.Text
	Website   pgtype.Text
	Ogrn      pgtype.Text
	Okpo      pgtype.Text
	Okato     pgtype.Text
	CreatedTs pgtype.Timestamp
	CreatedBy pgtype.Text
}

func (q *Queries) CreateInsuranceCompany(ctx context.Context, arg CreateInsuranceCompanyParams) (int32, error) {
	row := q.db.QueryRow(ctx, createInsuranceCompany,
		arg.Type,
		arg.Name,
		arg.FullName,
		arg.Address,
		arg.Phone,
		arg.Email,
		arg.Website,
		arg.Ogrn,
		arg.Okpo,
		arg.Okato,
		arg.CreatedTs,
		arg.CreatedBy,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}
