// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dbqueries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type InsuranceCompany struct {
	ID        int32
	Type      int32
	Name      string
	FullName  string
	Address   pgtype.Text
	Phone     pgtype.Text
	Email     pgtype.Text
	Website   pgtype.Text
	Ogrn      pgtype.Text
	Okpo      pgtype.Text
	Okato     pgtype.Text
	CreatedTs pgtype.Timestamp
	CreatedBy pgtype.Text
	UpdatedTs pgtype.Timestamp
	UpdatedBy pgtype.Text
	DeletedTs pgtype.Timestamp
	DeletedBy pgtype.Text
	Version   pgtype.Int4
}
